# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e413f03b9ea9af25bff705c69600f4a2292234fe095d22a3b3b62a3c54da67ea6c496206319b96de99ab36753fdd9f95f4def199524886d9e39740e97e1d96d7

test:
  secret_key_base: 45bc57fe249fb50ec2e7cab7e6792247053880755fe6c8c675850428f18afa40c9d8a68e61759b4f9568c944c02c3c58ae00abf8e8f803c397d1bea7d1da1df3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
